
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/managed_identity?ref=dev%2Fsandbox"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

dependency "solution_settings" {
  config_path = "../../solution_settings"

  mock_outputs = include.root.locals.mocks.solution_settings[include.root.locals.domain_name]

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "deep_map_only"
}

dependency "resource_group" {
  config_path = "../../resource_group"

  mock_outputs = include.root.locals.mocks.resource_group

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "aks_cluster" {
  config_path = "../cluster"

  mock_outputs = include.root.locals.mocks.aks_cluster

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

locals {
  name_prefix = "certmanager"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Shared solution settings. Explicit module inputs take precedence over these defaults.
  # Type: object
  settings = dependency.solution_settings.outputs.settings

  # Description: The name of the existing resource group.
  # Type: string
  resource_group_name = dependency.resource_group.outputs.name


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Optional federated identity credentials keyed by credential name. Each credential trusts an issuer and subject for the specified audience.
  # Type: map
  federated_identity_credentials = {
    certmanager = {
      issuer   = dependency.aks_cluster.outputs.oidc_issuer_url
      subject  = "system:serviceaccount:cert-manager:cert-manager"
      audience = ["api://AzureADTokenExchange"]
    }
  }

  # Description: Optional resource name override. Defaults to settings.name_prefix followed by id.
  # Type: string
  name = lower("${local.name_prefix}${include.root.locals.region_short}${include.root.locals.environment}mi")

  # Description: Optional Azure region override. Defaults to settings.region_long.
  # Type: string
  # location = null

  # Description: Tags to assign to the resource.
  # Type: map
  tags = dependency.solution_settings.outputs.tags

}
