
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "${path_relative_from_include()}/modules/base_aad_groups"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Application or platform prefix for group names, for example ATLAS.
  # Type: string
  group_prefix = include.root.locals.domain_name

  # Description: Region label used in group names, for example EUS2. Groups themselves are tenant-wide.
  # Type: string
  region = include.root.locals.region_short

  # Description: Environment label used in group names, for example DEV.
  # Type: string
  environment = include.root.locals.environment


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Object IDs of owners assigned to all three groups. Owners are not automatically members.
  # Type: set
  # owners = []

  # Description: Direct member object IDs keyed by READER, WRITER, or ADMIN. Omitted roles have no additional direct members.
  # Type: map
  # members = {}

}
