site_name: "Platform Infrastructure"
site_description: "Main repository to hold multi cloud infrastructure provisioned using terraform and terragrunt."
nav:
  - Home: index.md
  - Deployments: terragrunt.md
  - Azure pipelines: azure-pipelines.md
  - Azure groups: azure-groups.md
  - Architecture: architecture.md
plugins:
  - techdocs-core
