
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/ad_group?ref=dev%2Fsandbox"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

dependency "solution_settings" {
  config_path = "../../solution_settings"

  mock_outputs = include.root.locals.mocks.solution_settings[include.root.locals.domain_name]

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.shared_platform_allowed_commands
  mock_outputs_merge_strategy_with_state  = "deep_map_only"
}


inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Security groups keyed by display name, with optional descriptions, owners, members, and duplicate-name prevention.
  # Type: map
  groups = {
    "AKS-AGIC-ADMIN" = {
      description = "Administrators for the AKS cluster"
      owners      = [dependency.solution_settings.outputs.settings.object_id]
      members     = [dependency.solution_settings.outputs.settings.object_id]
    }
  }

  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

}
