
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/networking/nsg?ref=${urlencode(include.envcommon.locals.nsg)}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/module-versions.hcl"
  expose = true
}

dependency "vnet" {
  config_path = "../vnet"

  mock_outputs = {
    subnet_ids = {
      appsnet-001 = "/subscriptions/mock/resourceGroups/mock/providers/Microsoft.Network/virtualNetworks/mock/subnets/aksnet-001"
    }
  }
}

dependency "resource_group" {
  config_path = "../resource_group"
  mock_outputs = {
    name     = "mock-resource_group-output"
    location = "mock-location-output"
  }
}

dependency "solution_settings"{
  config_path = "../solution_settings"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Shared solution settings. Explicit module inputs take precedence over these defaults.
  # Type: object
  settings = dependency.solution_settings.outputs.settings

  # Description: The resource name.
  # Type: string
  name = lower("${include.root.locals.domain_name}${include.root.locals.region_short}${include.root.locals.environment}appnsg")

  # Description: The name of the existing resource group.
  # Type: string
  resource_group_name = dependency.resource_group.outputs.name

  # Description: The Azure region in which to create the resource.
  # Type: string
  location = dependency.resource_group.outputs.location


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Tags to assign to the resource.
  # Type: map
  # tags = {}

  # Description: Subnet ids to assign to the resource.
  # Type: map
  subnet_ids = {
    appsnet-001 = dependency.vnet.outputs.subnet_ids["appsnet-001"]
  }

  # Description: Custom security rules keyed by Azure rule name. An empty map creates no custom rules.
  # Type: map
  rules = {
    allow-https-to-vnet = {
      description                = "Allow the application to reach private VNet services over HTTPS"
      priority                   = 100
      direction                  = "Outbound"
      access                     = "Allow"
      protocol                   = "Tcp"
      source_address_prefix      = "*"
      destination_address_prefix = "VirtualNetwork"
      destination_port_range     = "443"
    }

    deny-other-vnet-traffic = {
      description                = "Block other traffic from the application integration subnet"
      priority                   = 200
      direction                  = "Outbound"
      access                     = "Deny"
      protocol                   = "*"
      source_address_prefix      = "*"
      destination_address_prefix = "VirtualNetwork"
      destination_port_range     = "*"
    }
  }
}
