
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/rbac?ref=${urlencode(include.envcommon.locals.rbac)}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/module-versions.hcl"
  expose = true
}

dependency "base_aad_groups" {
  config_path = "../../base_aad_groups"

  mock_outputs = include.root.locals.mocks.base_aad_groups

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "deep_map_only"
}

dependency "vnet" {
  config_path = "../../vnet"

  mock_outputs = include.root.locals.mocks.vnet

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "dns" {
  config_path = "../../dns"

  mock_outputs = include.root.locals.mocks.dns

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "aks_cluster" {
  config_path = "../cluster"

  mock_outputs = include.root.locals.mocks.aks_cluster

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Role assignments keyed by stable, caller-chosen names. Keys must be known at plan time; values may use dependency outputs.
  # Type: map
  assignments = {
    # required to allow app routing identity perms to manage records in DNS
    aks_cluster_web_app_identity = {
      scope                = dependency.dns.outputs.id
      principal_id         = dependency.aks_cluster.outputs.web_app_routing_identity[0].object_id
      type                 = "ServicePrincipal"
      role_definition_name = "DNS Zone Contributor"
    },
    aks_subnet_network = {
      scope                = dependency.vnet.outputs.subnet_ids["aksnet-001"]
      principal_id         = dependency.aks_cluster.outputs.identity[0].principal_id
      type                 = "ServicePrincipal"
      role_definition_name = "Network Contributor"
    }
  }


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

}
