
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/aks/cluster?ref=${urlencode(include.envcommon.locals.aks_cluster)}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/module-versions.hcl"
  expose = true
}

dependency "resource_group" {
  config_path = "../resource_group"
  mock_outputs = {
    name     = "mock-resource_group-output"
    location = "mock-location-output"
  }
}

dependency "solution_settings" {
  config_path = "../solution_settings"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Shared solution settings. Explicit module inputs take precedence over these defaults.
  # Type: object
  settings = dependency.solution_settings.outputs.settings

  # Description: The name of the existing resource group.
  # Type: string
  resource_group_name = dependency.resource_group.outputs.name

  # Description: The DNS prefix for the AKS cluster.
  # Type: string
  dns_prefix = "atlas"


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Optional resource name override. Defaults to settings.name_prefix followed by aks.
  # Type: string
  # name = null

  # Description: Optional Azure region override. Defaults to settings.region_long.
  # Type: string
  # location = null

  # Description: Tags to assign to the resource.
  # Type: map
  tags = dependency.solution_settings.outputs.tags

  # Description: The Kubernetes version. Null uses the regional Azure default.
  # Type: string
  # kubernetes_version = "1.37"

  # Description: Settings for the default Linux node pool. Omitted attributes use the module defaults.
  # Type: object
  default_node_pool = {
    vm_size              = "Standard_D4ads_v7"
    node_count           = 2
    auto_scaling_enabled = false
  }

  # Description: User-assigned identity resource IDs. An empty set uses a system-assigned identity.
  # Type: set
  # identity_ids = []

  # Description: Microsoft Entra group object IDs for cluster administrators.
  # Type: set
  # admin_group_object_ids = []

  # Description: Whether to create a private API server endpoint.
  # Type: bool
  private_cluster_enabled = false

  # Description: Whether to enable the OIDC issuer.
  # Type: bool
  # oidc_issuer_enabled = true

  # Description: Whether to enable workload identity. Requires the OIDC issuer.
  # Type: bool
  # workload_identity_enabled = true

  # Description: The AKS pricing tier.
  # Type: string
  sku_tier = "Free"

  # Description: Whether local accounts are disabled. Null disables them when Entra integration is enabled.
  # Type: bool
  # local_account_disabled = null

  # Description: The Entra tenant ID. Supplying this enables Entra integration even without administrator groups.
  # Type: string
  # tenant_id = null

  # Description: Whether Entra integration uses Azure RBAC rather than Kubernetes RBAC.
  # Type: bool
  azure_rbac_enabled = false

  # Description: Managed Prometheus metrics settings. Null disables the addon.
  # Type: object
  monitor_metrics = {}

  # Description: Application routing settings and Azure DNS zone IDs. Null disables the addon.
  # Type: object
  web_app_routing = {}

}
