
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/aks/extension?ref=${include.envcommon.locals.aks_extension_version}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/module-versions.hcl"
  expose = true
}

dependency "solution_settings" {
  config_path = "../solution_settings"
  mock_outputs = {
    settings = {
      solution_name   = "atlas"
      solution_slug   = "atlas"
      name_prefix     = "atlasuksdev"
      env             = "dev"
      region_short    = "uks"
      region_long     = "uksouth"
      subscription_id = "00000000-0000-0000-0000-000000000000"
      tenant_id       = "00000000-0000-0000-0000-000000000000"
      client_id       = "00000000-0000-0000-0000-000000000000"
      object_id       = "00000000-0000-0000-0000-000000000000"
    }
    tags = {
      Environement = "dev"
      Solution     = "Atlas"
      Region       = "uksouth"
    }
  }
  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

dependency "aks_cluster" {
  config_path = "../aks_cluster"
  mock_outputs = {
    id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mock-resource-group/providers/Microsoft.ContainerService/managedClusters/mock-aks"
  }
  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Shared solution settings used to generate the default name.
  # Type: object
  settings = dependency.solution_settings.outputs.settings

  # Description: The resource ID of the AKS cluster.
  # Type: string
  cluster_id = dependency.aks_cluster.outputs.id

  # Description: The extension type and its deployment settings. Use one module instance per extension.
  # Type: object
  extension = {
    extension_type = "Microsoft.ArgoCD"
    name           = "argocd-ext"
    release_train  = "preview"
    configuration_settings = {
      "redis-ha.enabled"         = "false"
      "server.service.type"      = "ClusterIP"
      deployWithHighAvailability = "false"
      namespaceInstall           = "false"
    }
  }

  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Sensitive extension settings. These values are still stored in Terraform state.
  # Type: map
  # configuration_protected_settings = {}

}
