
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/aks/cluster?ref=${urlencode(include.envcommon.locals.aks_cluster)}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/module-versions.hcl"
  expose = true
}

dependency "resource_group" {
  config_path = "../../resource_group"

  mock_outputs = include.root.locals.mocks.resource_group

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "solution_settings" {
  config_path = "../../solution_settings"

  mock_outputs = include.root.locals.mocks.solution_settings[include.root.locals.domain_name]

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "deep_map_only"
}

dependency "dns" {
  config_path = "../../dns"

  mock_outputs = include.root.locals.mocks.dns

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "vnet" {
  config_path = "../../vnet"

  mock_outputs = include.root.locals.mocks.vnet

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}


locals {
  name_prefix = "approuting"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Shared solution settings. Explicit module inputs take precedence over these defaults.
  # Type: object
  settings = dependency.solution_settings.outputs.settings

  # Description: The name of the existing resource group.
  # Type: string
  resource_group_name = dependency.resource_group.outputs.name

  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Optional resource name override. Defaults to settings.name_prefix followed by aks.
  # Type: string
  name = lower("${local.name_prefix}${include.root.locals.region_short}${include.root.locals.environment}aks")

  # Description: Optional Azure region override. Defaults to settings.region_long.
  # Type: string
  # location = null

  # Description: Tags to assign to the resource.
  # Type: map
  tags = dependency.solution_settings.outputs.tags

  # Description: The DNS prefix for the AKS cluster. Set exactly one of dns_prefix or dns_prefix_private_cluster.
  # Type: string
  dns_prefix = lower("${dependency.solution_settings.outputs.settings.name_prefix}aks")

  # Description: The Kubernetes version. Null uses the regional Azure default.
  # Type: string
  # kubernetes_version = "1.37"

  # Description: Settings for the default Linux node pool. Omitted attributes use the module defaults.
  # Type: object
  default_node_pool = {
    vm_size              = "Standard_D2_v5"
    auto_scaling_enabled = true
    min_count            = 3
    max_count            = 5
    max_pods             = 30
    vnet_subnet_id       = dependency.vnet.outputs.subnet_ids["aksnet-001"]
  }

  # Description: User-assigned identity resource IDs. An empty set uses a system-assigned identity.
  # Type: set
  # identity_ids = []

  # Description: Microsoft Entra group object IDs for cluster administrators.
  # Type: set
  # admin_group_object_ids = []

  # Description: Whether to create a private API server endpoint.
  # Type: bool
  private_cluster_enabled = false

  # Description: Whether to enable the OIDC issuer.
  # Type: bool
  # oidc_issuer_enabled = true

  # Description: Whether to enable workload identity. Requires the OIDC issuer.
  # Type: bool
  # workload_identity_enabled = true

  # Description: The AKS pricing tier.
  # Type: string
  # sku_tier = "Free"

  # Description: Whether local accounts are disabled. Null disables them when Entra integration is enabled.
  # Type: bool
  # local_account_disabled = null

  # Description: The Entra tenant ID. Supplying this enables Entra integration even without administrator groups.
  # Type: string
  # tenant_id = null

  # Description: Whether Entra integration uses Azure RBAC rather than Kubernetes RBAC.
  # Type: bool
  azure_rbac_enabled = false

  # Description: Managed Prometheus metrics settings. Null disables the addon.
  # Type: object
  # monitor_metrics = {}

  # Description: Application routing settings and Azure DNS zone IDs. Null disables the addon.
  # Type: object
  web_app_routing = {
    dns_zone_ids             = [dependency.dns.outputs.id]
    default_nginx_controller = "External"
  }

  # Description: Private cluster DNS prefix. Use instead of dns_prefix with a private cluster and a custom private DNS zone.
  # Type: string
  # dns_prefix_private_cluster = null

  # Description: Private DNS zone resource ID, System, or None. Null uses the AKS default. Custom zones require caller-managed identity permissions.
  # Type: string
  # private_dns_zone_id = null

  # Description: Existing kubelet identity. Requires a user-assigned control-plane identity and caller-managed assignment permissions.
  # Type: object
  kubelet_identity = null

  # Description: AKS networking configuration. The default preserves Azure CNI overlay networking.
  # Type: object
  # network_profile = {"network_plugin":"azure","network_plugin_mode":"overlay"}

  # Description: Application Gateway ingress using an existing gateway. Null disables the addon.
  # Type: object
  ingress_application_gateway = null

  # Description: Kubernetes secret encryption with an existing Key Vault key. Null disables KMS. Key permissions and private connectivity are caller-managed.
  # Type: object
  key_management_service = null

  # Description: Container Insights with an existing Log Analytics workspace. Null disables the addon.
  # Type: object
  oms_agent = null

}
