
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/rbac?ref=${urlencode(include.envcommon.locals.rbac)}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/module-versions.hcl"
  expose = true
}

dependency "base_aad_groups" {
  config_path = "../base_aad_groups"

  mock_outputs = include.root.locals.mocks.base_aad_groups

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.shared_platform_allowed_commands
  mock_outputs_merge_strategy_with_state  = "deep_map_only"
}

dependency "resource_group" {
  config_path = "../resource_group"

  mock_outputs = include.root.locals.mocks.resource_group

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.shared_platform_allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Role assignments keyed by stable, caller-chosen names. Keys must be known at plan time; values may use dependency outputs.
  # Type: map
  assignments = {
    platform_reader = {
      scope                = dependency.resource_group.outputs.id
      principal_id         = dependency.base_aad_groups.outputs.object_ids["READER"]
      type                 = "Group"
      role_definition_name = "Reader"
    }
    platform_owner = {
      scope                = dependency.resource_group.outputs.id
      principal_id         = dependency.base_aad_groups.outputs.object_ids["ADMIN"]
      type                 = "Group"
      role_definition_name = "Contributor"
    }
  }


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

}
