
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/aks/extension?ref=feature%2Fk8s-terraform-modules"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

dependency "solution_settings" {
  config_path = "../solution_settings"
}

dependency "aks_cluster" {
  config_path = "../aks_cluster"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Shared solution settings used to generate the default name.
  # Type: object
  settings = dependency.solution_settings.outputs.settings

  # Description: The resource ID of the AKS cluster.
  # Type: string
  cluster_id = dependency.aks_cluster.outputs.id

  # Description: The extension type and its deployment settings. Use one module instance per extension.
  # Type: object
  extension = {
    extension_type = "Microsoft.ArgoCD"
    name           = "argocd-ext"
    release_train  = "preview"
    configuration_settings = {
      "redis-ha.enabled"         = "false"
      "server.service.type"      = "ClusterIP"
      deployWithHighAvailability = "false"
      namespaceInstall           = "false"
    }
  }

  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Sensitive extension settings. These values are still stored in Terraform state.
  # Type: map
  # configuration_protected_settings = {}

}
