
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/log_analytics?ref=dev%2Fsandbox"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

dependency "resource_group" {
  config_path = "../resource_group"

  mock_outputs = include.root.locals.mocks.resource_group

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.shared_platform_allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "solution_settings" {
  config_path = "../solution_settings"

  mock_outputs = include.root.locals.mocks.solution_settings[include.root.locals.domain_name]

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.shared_platform_allowed_commands
  mock_outputs_merge_strategy_with_state  = "deep_map_only"
}


inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Shared solution settings. Explicit module inputs take precedence over defaults.
  # Type: object
  settings = dependency.solution_settings.ouputs.settings

  # Description: The name of the existing resource group.
  # Type: string
  resource_group_name = dependency.resource_group.outputs.name


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Optional workspace name override. Defaults to settings.name_prefix followed by law.
  # Type: string
  # name = null

  # Description: Optional Azure region override. Defaults to settings.region_long.
  # Type: string
  # location = null

  # Description: The workspace pricing tier. Legacy tiers may be unavailable for new workspaces.
  # Type: string
  # sku = "PerGB2018"

  # Description: The workspace data retention period, from 30 to 730 days. Individual table settings can override this default.
  # Type: number
  # retention_in_days = 30

  # Description: The daily ingestion cap in GB. Set -1 for unlimited ingestion.
  # Type: number
  # daily_quota_gb = -1

  # Description: Allow shared-key authentication in addition to Microsoft Entra authentication. Disabled by default.
  # Type: bool
  # local_authentication_enabled = false

  # Description: Allow users to query logs for resources they can access without a workspace role assignment.
  # Type: bool
  # allow_resource_only_permissions = true

  # Description: Public ingestion access: Enabled, Disabled, or SecuredByPerimeter. Private connectivity or a perimeter must be provisioned separately.
  # Type: string
  # internet_ingestion_access_type = "Enabled"

  # Description: Public query access: Enabled, Disabled, or SecuredByPerimeter. Private connectivity or a perimeter must be provisioned separately.
  # Type: string
  # internet_query_access_type = "Enabled"

  # Description: Tags to assign to the workspace.
  # Type: map
  tags = dependency.solution_settings.outputs.tags

}
