
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/networking/application_gateway?ref=dev%2Fsandbox"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

dependency "solution_settings" {
  config_path = "../../solution_settings"
}

dependency "resource_group" {
  config_path = "../../resource_group"
}

dependency "vnet" {
  config_path = "../../vnet"
}

dependency "agic_uami" {
  config_path = "../agic_uami"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Shared naming and region defaults. Explicit inputs take precedence.
  # Type: object
  settings = dependency.solution_settings.outputs.settings

  # Description: The existing resource group name.
  # Type: string
  resource_group_name = dependency.resource_group.outputs.name

  # Description: The dedicated Application Gateway subnet resource ID.
  # Type: string
  subnet_id = dependency.vnet.outputs.subnet_ids["agwsnet-001"]

  # Description: Frontend configurations keyed by name. Each references a public IP or specifies a static private IP on subnet_id.
  # Type: map
  frontend_ip_configurations = {}

  # Type: bool
  add_public_ip_address = true

  # Type: string
  public_ip_configuration_name = "public"

  # Description: Frontend TCP ports keyed by name.
  # Type: map
  frontend_ports = {
    bootstrap_ports = {
      bootstrap-http = 80 # initial configs. To be managed by AGIC
    }
  }

  # Description: Backend pools keyed by name. Empty pools can be populated later.
  # Type: map
  backend_address_pools = {
    bootstrap = { # to be managed by AGIC
      fqdns        = []
      ip_addresses = []
    }
  }

  # Description: Backend HTTP settings keyed by name. Use HTTPS and trusted certificates for encrypted backend traffic.
  # Type: map
  backend_http_settings = {
    bootstrap = { # to be managed by AGIC
      port                                = 80
      protocol                            = "Http"
      cookie_based_affinity               = "Disabled"
      request_timeout                     = 30
      host_name                           = null
      pick_host_name_from_backend_address = false
      path                                = null
      probe_name                          = null
      trusted_root_certificate_names      = []
      connection_draining                 = null
    }
  }

  # Description: Listeners keyed by name. HTTPS requires a named Key Vault certificate.
  # Type: map
  http_listeners = {
    bootstrap = {
      frontend_ip_configuration_name = "public"         # same name as var.public_ip_configuration_name
      frontend_port_name             = "bootstrap-http" # reference frontend_ports
      protocol                       = "Http"
      host_name                      = null
      host_names                     = []
      require_sni                    = false
      ssl_certificate_name           = null
    }
  }

  # Description: Basic or path-based routing rules keyed by name. Priorities must be unique.
  # Type: map
  request_routing_rules = {
    bootstrap = { # to be managed by AGIC
      priority                   = 100
      http_listener_name         = "bootstrap"
      rule_type                  = "Basic"
      backend_address_pool_name  = "bootstrap"
      backend_http_settings_name = "bootstrap"
      url_path_map_name          = null
    }
  }


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Name override. Defaults to settings.name_prefix followed by agw.
  # Type: string
  # name = null

  # Description: Region override. Defaults to settings.region_long.
  # Type: string
  # location = null

  # Description: Tags for the gateway.
  # Type: map
  tags = dependency.solution_settings.outputs.tags

  # Description: Application Gateway v2 SKU and fixed capacity. Capacity is omitted when autoscaling is configured.
  # Type: object
  sku = {
    tier     = "Standard_v2"
    capacity = 1 # Fixed single instance for the lab.
  }

  # Description: Optional autoscaling bounds. Null uses fixed SKU capacity.
  # Type: object
  autoscale_configuration = null

  # Description: Availability zones. Confirm regional support before deployment.
  # Type: set
  # zones = []

  # Description: Enable HTTP/2 on frontend listeners.
  # Type: bool
  # http2_enabled = true

  # Description: User-assigned identity resource IDs, required for Key Vault certificates. Permissions remain caller-managed.
  # Type: set
  identity_ids = [dependency.agic_uami.outputs.id]

  # Description: Existing WAF policy resource ID. Requires WAF_v2.
  # Type: string
  # firewall_policy_id = null

  # Description: Path maps keyed by name. Path rules are ordered lists because matching order matters.
  # Type: map
  # url_path_maps = {}

  # Description: Health probes keyed by name. Specify host or pick_host_name_from_backend_http_settings.
  # Type: map
  # probes = {}

  # Description: Key Vault certificate secret IDs keyed by certificate name. Prefer versionless secret IDs for rotation.
  # Type: map
  # ssl_certificates = {}

  # Description: Base64-encoded backend root certificates keyed by name.
  # Type: map
  # trusted_root_certificates = {}

  # Description: Predefined frontend TLS policy.
  # Type: string
  # ssl_policy_name = "AppGwSslPolicy20220101S"

}
