
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/managed_identity?ref=dev%2Fsandbox"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

dependency "solution_settings" {
  config_path = "../../solution_settings"
}

dependency "resource_group" {
  config_path = "../../resource_group"
}

locals {
  name_prefix = "kubelet"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Shared solution settings. Explicit module inputs take precedence over these defaults.
  # Type: object
  settings = dependency.solution_settings.outputs.settings

  # Description: The name of the existing resource group.
  # Type: string
  resource_group_name = dependency.resource_group.outputs.name


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Optional federated identity credentials keyed by credential name. Each credential trusts an issuer and subject for the specified audience.
  # Type: map
  # federated_identity_credentials = {}

  # Description: Optional resource name override. Defaults to settings.name_prefix followed by id.
  # Type: string
  name = lower("${local.name_prefix}${include.root.locals.region_short}${include.root.locals.environment}mi")

  # Description: Optional Azure region override. Defaults to settings.region_long.
  # Type: string
  # location = null

  # Description: Tags to assign to the resource.
  # Type: map
  tags = dependency.solution_settings.outputs.tags

}
