
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/rbac?ref=${urlencode(include.envcommon.locals.rbac)}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/module-versions.hcl"
  expose = true
}

dependency "base_aad_groups" {
  config_path = "../../base_aad_groups"

  mock_outputs = include.root.locals.mocks.base_aad_groups

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "deep_map_only"
}

dependency "vnet" {
  config_path = "../../vnet"

  mock_outputs = include.root.locals.mocks.vnet

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "dns" {
  config_path = "../../dns"

  mock_outputs = include.root.locals.mocks.dns

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "aks_cluster" {
  config_path = "../cluster"

  mock_outputs = include.root.locals.mocks.aks_cluster

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "resource_group" {
  config_path = "../../resource_group"
}

dependency "application_gateway" {
  config_path = "../application_gateway"
}

dependency "cluster_ad_groups" {
  config_path = "../cluster"
}

dependency "agic_uami" {
  config_path = "../agic_uami"
}

dependency "certmanager_uami" {
  config_path = "../certmanager_uami"
}

dependency "controlplane_uami" {
  config_path = "../controlplane_uami"
}

dependency "externaldns_uami" {
  config_path = "../externaldns_uami"
}

dependency "kubelet_uami" {
  config_path = "../kubelet_uami"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Role assignments keyed by stable, caller-chosen names. Keys must be known at plan time; values may use dependency outputs.
  # Type: map
  assignments = {
    # # Grants the admin group full Kubernetes API access across the cluster
    aks_cluster_admin = {
      scope                = dependency.aks_cluster.outputs.id
      principal_id         = dependency.cluster_ad_groups.outputs.object_ids["AKS-AGIC-ADMIN"]
      type                 = "Group"
      role_definition_name = "Azure Kubernetes Service RBAC Cluster Admin"
    },
    controlplane_subnet = {
      scope                = dependency.vnet.outputs.subnet_ids["aksnet-001"]
      principal_id         = dependency.controlplane_uami.outputs.principal_id
      type                 = "ServicePrincipal"
      role_definition_name = "Network Contributor"
    },
    # Allows AKS to assign that identity to its nodes
    controlplane_kubelet = {
      scope                = dependency.kubelet_uami.outputs.id
      principal_id         = dependency.controlplane_uami.outputs.principal_id
      type                 = "ServicePrincipal"
      role_definition_name = "Managed Identity Operator"
    },
    # Allows kublet for each pod to pull images!
    kubelet_acr = {
      scope                = dependency.container_registry.outputs.id
      principal_id         = dependency.kubelet_uami.outputs.principal_id
      type                 = "ServicePrincipal"
      role_definition_name = "AcrPull"
    },
    # Both RBACS are required for agic uami as per docs: https://learn.microsoft.com/en-us/azure/application-gateway/ingress-controller-install-existing
    agic_agw = {
      scope                = dependency.application_gateway.outputs.id
      principal_id         = dependency.agic_uami.outputs.principal_id
      type                 = "ServicePrincipal"
      role_definition_name = "Contributor"
    },
    agic_rg = {
      scope                = dependency.resource_group.outputs.id
      principal_id         = dependency.agic_uami.outputs.principal_id
      type                 = "ServicePrincipal"
      role_definition_name = "Reader"
    },
    agic_agw_identity = {
      # Resource ID of the UAMI attached to Application Gateway
      scope                = dependency.agic_uami.outputs.id
      principal_id         = dependency.agic_uami.outputs.principal_id
      type                 = "ServicePrincipal"
      role_definition_name = "Managed Identity Operator"
    },
    # both are required: https://kubernetes-sigs.github.io/external-dns/latest/docs/tutorials/azure/#managed-identity-using-workload-identity
    externaldns_network = {
      scope                = dependency.dns.outputs.id
      principal_id         = dependency.externaldns_uami.outputs.principal_id
      type                 = "ServicePrincipal"
      role_definition_name = "DNS Zone Contributor"
    },
    externaldns_network_reader = {
      scope                = dependency.resource_group.outputs.id
      principal_id         = dependency.externaldns_uami.outputs.principal_id
      type                 = "ServicePrincipal"
      role_definition_name = "Reader"
    },
    # Creates _acme-challenge TXT records for certificate validation. Not needed currently because of HTTP-01 but later for Azure DNS DNS-0
    certmanager_uami = {
      scope                = dependency.dns.outputs.id
      principal_id         = dependency.certmanager_uami.outputs.principal_id
      type                 = "ServicePrincipal"
      role_definition_name = "DNS Zone Contributor"
    },
  }


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

}
