
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "${include.root.locals.repo_urls.platform_blueprints_github_url}//terraform/shared/kubernetes_manifest?ref=${urlencode(include.envcommon.locals.kubernetes_manifest)}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/module-versions.hcl"
  expose = true
}

dependencies {
  paths = ["../aks_argocd_extension"]
}

dependency "aks" {
  config_path = "../aks_cluster"

  mock_outputs = include.root.locals.mocks.aks_cluster

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

generate "kubernetes_provider" {
  path      = "provider-kubernetes.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    provider "kubernetes" {
      host                   = "${dependency.aks.outputs.host}"
      cluster_ca_certificate = base64decode("${dependency.aks.outputs.cluster_ca_certificate}")
      client_certificate     = base64decode("${dependency.aks.outputs.client_certificate}")
      client_key             = base64decode("${dependency.aks.outputs.client_key}")
    }
  EOF
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: A single Kubernetes manifest as an HCL object or yamldecode() result. Custom resource definitions must already exist before planning.
  # Type: any
  manifest = {
    apiVersion = "argoproj.io/v1alpha1"
    kind       = "Application"

    metadata = {
      name      = "all-apps"
      namespace = "argocd"

      # Cascade deletion of resources managed by this Application.
      finalizers = ["resources-finalizer.argocd.argoproj.io"]
    }

    spec = {
      project = "default"

      source = {
        repoURL        = "https://github.com/RyanJKS/platform-gitops.git"
        targetRevision = "main"

        path = "clusters/azure/${include.root.locals.subscription_name}/${include.root.locals.environment}/${include.root.locals.region_short}/${include.root.locals.domain_name}/aks-shared/argocd"
      }

      destination = {
        server    = "https://kubernetes.default.svc"
        namespace = "argocd"
      }

      syncPolicy = {
        automated = {
          prune    = true
          selfHeal = true
        }

        syncOptions = [
          "ServerSideApply=true",
          "PrunePropagationPolicy=foreground",
          "PruneLast=true",
        ]
      }
    }
  }

  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Manifest field paths that Kubernetes or controllers may change without causing inconsistent result errors.
  # Type: list
  # computed_fields = ["metadata.annotations","metadata.labels"]

  # Description: Server-side apply field ownership settings. Enable force_conflicts only when intentionally taking ownership from another manager.
  # Type: object
  # field_manager = {}

  # Description: Optional field paths and regular expressions to wait for after applying, such as status.health.status = Healthy for an Argo CD Application. Null disables waiting.
  # Type: map
  wait_fields = {}

  # Description: Create, update, and delete timeouts as duration strings.
  # Type: object
  # timeouts = {}

}
