
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/networking/vnet?ref=feature%2Fazure-terraform-modules"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The resource name.
  # Type: string
  name = "lower(\"${include.root.locals.spoke_prefix}${include.root.locals.region_short}{include.root.locals.environment}vnet\")"

  # Description: The name of the existing resource group.
  # Type: string
  resource_group_name = "ha"

  # Description: The Azure region in which to create the resource.
  # Type: string
  location = "ha"

  # Description: The address ranges for the virtual network.
  # Type: list
  address_space = []


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Tags to assign to the resource.
  # Type: map
  # tags = {}

  # Description: Custom DNS servers. An empty list uses Azure DNS.
  # Type: list
  # dns_servers = []

  # Description: Subnets keyed by subnet name.
  # Type: map
  # subnets = {}

}
