
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/networking/vnet?ref=${include.envcommon.locals.vnet}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/module-versions.hcl"
  expose = true
}

include "network_addresses" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/network-addresses.hcl"
  expose = true
}

dependency "resource_group" {
  config_path = "../resource_group"
  mock_outputs = {
    name     = "mock-resource_group-output"
    location = "mock-location-output"
  }
}

dependency "solution_settings"{
  config_path = "../solution_settings"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Shared solution settings. Explicit module inputs take precedence over these defaults.
  # Type: object
  settings = dependency.solution_settings.outputs.settings

  # Description: The resource name.
  # Type: string
  name = lower("${include.root.locals.domain_name}${include.root.locals.region_short}${include.root.locals.environment}vnet")

  # Description: The name of the existing resource group.
  # Type: string
  resource_group_name = dependency.resource_group.outputs.name

  # Description: The Azure region in which to create the resource.
  # Type: string
  location = dependency.resource_group.outputs.location

  # Description: The address ranges for the virtual network.
  # Type: list
  address_space = include.network_addresses.locals.address_spaces[include.root.locals.subscription_name][include.root.locals.environment][include.root.locals.region_short][include.root.locals.domain_name]


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Tags to assign to the resource.
  # Type: map
  # tags = {}

  # Description: Custom DNS servers. An empty list uses Azure DNS.
  # Type: list
  # dns_servers = []
  subnets = {
    aksnet-001 = {
      address_prefixes = ["10.0.1.0/24"]
    }
    aksnet-002 = {
      address_prefixes = ["10.0.2.0/24"]
    }


    appsnet-001 = {
      address_prefixes  = ["10.0.6.0/24"]
      service_endpoints = ["Microsoft.Storage"]

      delegation = {
        name = "app-service-delegation"

        service_delegation = {
          name = "Microsoft.Web/serverFarms"

          actions = [
            "Microsoft.Network/virtualNetworks/subnets/action"
          ]
        }
      }
    }
  }
}
