
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "${include.root.locals.repo_urls.platform_blueprints_github_url}//terraform/azure/networking/nsg?ref=${urlencode(include.envcommon.locals.nsg)}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/module-versions.hcl"
  expose = true
}

dependency "vnet" {
  config_path = "../../vnet"

  mock_outputs = include.root.locals.mocks.vnet

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.shared_platform_allowed_commands
  mock_outputs_merge_strategy_with_state  = "deep_map_only"
}

dependency "resource_group" {
  config_path = "../../resource_group"

  mock_outputs = include.root.locals.mocks.resource_group

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.shared_platform_allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "solution_settings" {
  config_path = "../../solution_settings"

  mock_outputs = include.root.locals.mocks.solution_settings[include.root.locals.domain_name]

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.shared_platform_allowed_commands
  mock_outputs_merge_strategy_with_state  = "deep_map_only"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Shared solution settings. Explicit module inputs take precedence over these defaults.
  # Type: object
  settings = dependency.solution_settings.outputs.settings

  # Description: The resource name.
  # Type: string
  name = lower("${include.root.locals.domain_name}${include.root.locals.region_short}${include.root.locals.environment}agwnsg")

  # Description: The name of the existing resource group.
  # Type: string
  resource_group_name = dependency.resource_group.outputs.name

  # Description: The Azure region in which to create the resource.
  # Type: string
  location = dependency.resource_group.outputs.location


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Tags to assign to the resource.
  # Type: map
  tags = dependency.solution_settings.outputs.tags

  # Description: Subnet ids to assign to the resource.
  # Type: map
  subnet_ids = {
    agwsnet-001 = dependency.vnet.outputs.subnet_ids["agwsnet-001"]
  }

  # Description: Custom security rules keyed by Azure rule name. An empty map creates no custom rules.
  # Type: map
  rules = {
    allow-http = {
      description                = "Allow HTTP access and Let's Encrypt HTTP-01 validation"
      priority                   = 100
      direction                  = "Inbound"
      access                     = "Allow"
      protocol                   = "Tcp"
      source_address_prefix      = "Internet"
      destination_address_prefix = "10.2.3.0/24"
      destination_port_range     = "80"
    }

    allow-https = {
      description                = "Allow public HTTPS access to application listeners"
      priority                   = 110
      direction                  = "Inbound"
      access                     = "Allow"
      protocol                   = "Tcp"
      source_address_prefix      = "Internet"
      destination_address_prefix = "10.2.3.0/24"
      destination_port_range     = "443"
    }

    allow-gateway-manager = {
      description                = "Allow required Application Gateway v2 infrastructure traffic"
      priority                   = 120
      direction                  = "Inbound"
      access                     = "Allow"
      protocol                   = "Tcp"
      source_address_prefix      = "GatewayManager"
      destination_address_prefix = "*"
      destination_port_range     = "65200-65535"
    }

    allow-azure-load-balancer = {
      description                = "Preserve Azure platform probes before the explicit deny rule"
      priority                   = 130
      direction                  = "Inbound"
      access                     = "Allow"
      protocol                   = "*"
      source_address_prefix      = "AzureLoadBalancer"
      destination_address_prefix = "*"
      destination_port_range     = "*"
    }

    deny-other-inbound = {
      description                = "Block inbound traffic not explicitly allowed above"
      priority                   = 200
      direction                  = "Inbound"
      access                     = "Deny"
      protocol                   = "*"
      source_address_prefix      = "*"
      destination_address_prefix = "*"
      destination_port_range     = "*"
    }
  }
}
