
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/resource_group?ref=${urlencode(include.envcommon.locals.resource_group)}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/module-versions.hcl"
  expose = true
}

dependency "solution_settings" {
  config_path = "../solution_settings"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The name of the Azure resource group.
  # Type: string
  name = upper("${include.root.locals.domain_name}-NETWORK-${include.root.locals.region_short}-${include.root.locals.environment}-RG")

  # Description: The Azure region in which to create the resource group, such as uksouth.
  # Type: string
  location = lower("${include.root.locals.region_long}")


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Tags to assign to the resource group.
  # Type: map
  tags = dependency.solution_settings.outputs.tags

}
