
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/solution_settings?ref=${urlencode(include.envcommon.locals.solution_settings)}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/module-versions.hcl"
  expose = true
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The solution name shared by consuming modules.
  # Type: string
  solution_name = include.root.locals.spoke_prefix

  # Description: The environment name, such as dev, staging, or prod.
  # Type: string
  env = include.root.locals.environment

  # Description: The region abbreviation used in resource names, such as uks.
  # Type: string
  region_short = include.root.locals.region_short

  # Description: The Azure location identifier, such as uksouth.
  # Type: string
  region_long = include.root.locals.region_long


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Shared tags. The module passes these through without adding or overriding tags.
  # Type: map
  tags = {
    "Environement" : include.root.locals.environment,
    "Solution" : title(include.root.locals.spoke_prefix),
    "Region" : include.root.locals.region_long
  }

}
