
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/container_registry?ref=dev%2Fsandbox"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

dependency "solution_settings" {
  config_path = "../solution_settings"
}

dependency "resource_group" {
  config_path = "../resource_group"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Shared solution settings used for the registry name and Azure region.
  # Type: object
  settings = dependency.solution_settings.outputs.settings

  # Description: The name of the existing resource group.
  # Type: string
  resource_group_name = dependency.resource_group.outputs.name


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Optional globally unique registry name. Defaults to the lowercase alphanumeric settings.name_prefix followed by acr.
  # Type: string
  # name = null

  # Description: The registry pricing tier: Basic, Standard, or Premium.
  # Type: string
  # sku = "Basic"

  # Description: Enable the registry admin account. Prefer Microsoft Entra authentication and role assignments.
  # Type: bool
  # admin_enabled = false

  # Description: Allow unauthenticated image pulls. Requires Standard or Premium.
  # Type: bool
  # anonymous_pull_enabled = false

  # Description: Allow registry access through the public endpoint. Private endpoints are managed separately.
  # Type: bool
  # public_network_access_enabled = true

  # Description: Allow trusted Azure services to bypass network rules: AzureServices or None.
  # Type: string
  # network_rule_bypass_option = "AzureServices"

  # Description: Optional Premium network rules with an Allow or Deny default and IPv4 CIDR allow rules. Use null to omit network rules for Basic or Standard.
  # Type: object
  network_rule_set = null

  # Description: Enable dedicated data endpoints. Requires Premium.
  # Type: bool
  # data_endpoint_enabled = false

  # Description: Allow artifact exports. Disabling exports requires Premium and disabled public network access.
  # Type: bool
  # export_policy_enabled = true

  # Description: Enable zone redundancy in a supported region. Requires Premium.
  # Type: bool
  # zone_redundancy_enabled = false

  # Description: Optional registry identity. UserAssigned types require identity_ids. This identity does not grant clients access to images.
  # Type: object
  identity = null

  # Description: Optional Premium replicas in distinct Azure regions other than settings.region_long.
  # Type: list
  # georeplications = []

  # Description: Tags to assign to the registry. Replica tags are configured separately.
  # Type: map
  tags = dependency.solution_settings.outputs.tags

}
