
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "${include.root.locals.repo_urls.platform_blueprints_github_url}//terraform/azure/aks/extension?ref=${include.envcommon.locals.aks_extension_version}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/module-versions.hcl"
  expose = true
}

dependency "solution_settings" {
  config_path = "../../solution_settings"

  mock_outputs = include.root.locals.mocks.solution_settings[include.root.locals.domain_name]

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "deep_map_only"
}

dependency "aks_cluster" {
  config_path = "../cluster"

  mock_outputs = include.root.locals.mocks.aks_cluster

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

## EXTENSION CAN ONLY BE USED IF AKS CLUSTER HAS SYSTEM-ASSIGNED MANAGED IDENTITY: https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-use-gitops-argocd#azure-kubernetes-service-clusters

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Shared solution settings used to generate the default name.
  # Type: object
  settings = dependency.solution_settings.outputs.settings

  # Description: The resource ID of the AKS cluster.
  # Type: string
  cluster_id = dependency.aks_cluster.outputs.id

  # Description: The extension type and its deployment settings. Use one module instance per extension.
  # Type: object
  extension = {
    extension_type = "Microsoft.ArgoCD"
    name           = "argocd-ext"
    release_train  = "preview"
    configuration_settings = {
      deployWithHighAvailability = "false"
      namespaceInstall           = "false"

      "redis-ha.enabled"        = "false"
      "controller.replicas"     = "1"
      "repoServer.replicas"     = "1"
      "applicationSet.replicas" = "1"
      "server.replicas"         = "1"

      "global.domain"  = "argocd.jkslabs.site"
      "configs.cm.url" = "https://argocd.jkslabs.site"

      "server.service.type"             = "ClusterIP"
      "server.ingress.enabled"          = "true"
      "server.ingress.hostname"         = "argocd.jkslabs.site"
      "server.ingress.ingressClassName" = "webapprouting.kubernetes.azure.com"
      "server.ingress.tls"              = "true"

      "server.ingress.annotations.nginx\\.ingress\\.kubernetes\\.io/backend-protocol" = "HTTPS"
      "server.ingress.annotations.cert-manager\\.io/cluster-issuer"                   = "letsencrypt-prod"
    }
  }

  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Sensitive extension settings. These values are still stored in Terraform state.
  # Type: map
  # configuration_protected_settings = {}

}
