
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/keyvault?ref=dev%2Fsandbox"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

dependency "resource_group" {
  config_path = "../resource_group"

  mock_outputs = include.root.locals.mocks.resource_group

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.shared_platform_allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "solution_settings" {
  config_path = "../solution_settings"

  mock_outputs = include.root.locals.mocks.solution_settings[include.root.locals.domain_name]

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.shared_platform_allowed_commands
  mock_outputs_merge_strategy_with_state  = "deep_map_only"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Shared solution settings. Explicit module inputs take precedence over these defaults.
  # Type: object
  settings = dependency.solution_settings.outputs.settings

  # Description: The name of the existing resource group.
  # Type: string
  resource_group_name = dependency.resource_group.outputs.name


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Optional resource name override. Defaults to settings.name_prefix followed by akv.
  # Type: string
  # name = null

  # Description: Optional Azure region override. Defaults to settings.region_long.
  # Type: string
  # location = null

  # Description: Tags to assign to the resource.
  # Type: map
  tags = dependency.solution_settings.outputs.tags

  # Description: Optional tenant ID override. Defaults to settings.tenant_id.
  # Type: string
  # tenant_id = null

  # Description: The Key Vault SKU.
  # Type: string
  # sku_name = "standard"

  # Description: The retention period for deleted vaults and objects.
  # Type: number
  # soft_delete_retention_days = 90

  # Description: Whether to enable irreversible purge protection.
  # Type: bool
  # purge_protection_enabled = true

  # Description: Whether to allow access through the public endpoint.
  # Type: bool
  # public_network_access_enabled = false

}
