
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/rbac?ref=${urlencode(include.envcommon.locals.rbac)}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/module-versions.hcl"
  expose = true
}

dependency "base_aad_groups" {
  config_path = "../base_aad_groups"

  mock_outputs = {
    object_ids = {
      READER = "11111111-1111-1111-1111-111111111111"
      WRITER = "22222222-2222-2222-2222-222222222222"
      ADMIN  = "33333333-3333-3333-3333-333333333333"
    }
  }
  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

dependency "resource_group" {
  config_path = "../resource_group"
  mock_outputs = {
    id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mock-resource-group"
  }
  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Role assignments keyed by stable, caller-chosen names. Keys must be known at plan time; values may use dependency outputs.
  # Type: map
  assignments = {
    platform_reader = {
      scope                = dependency.resource_group.outputs.id
      principal_id         = dependency.base_aad_groups.outputs.object_ids["READER"]
      type                 = "Group"
      role_definition_name = "Reader"
    }
    platform_owner = {
      scope                = dependency.resource_group.outputs.id
      principal_id         = dependency.base_aad_groups.outputs.object_ids["ADMIN"]
      type                 = "Group"
      role_definition_name = "Contributor"
    }
  }


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

}
