
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git@github.com:RyanJKS/platform-blueprints.git//terraform/azure/rbac?ref=${urlencode(include.envcommon.locals.rbac)}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/module-versions.hcl"
  expose = true
}

dependency "vnet" {
  config_path = "../../vnet"

  mock_outputs = include.root.locals.mocks.vnet

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "deep_map_only"
}

dependency "controlplane_uami" {
  config_path = "../controlplane_uami"

  mock_outputs = include.root.locals.mocks.managed_identity

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

dependency "kubelet_uami" {
  config_path = "../kubelet_uami"

  mock_outputs = include.root.locals.mocks.managed_identity

  mock_outputs_allowed_terraform_commands = include.root.locals.mocks.allowed_commands
  mock_outputs_merge_strategy_with_state  = "shallow"
}

inputs = {
  # These permissions must exist before Azure creates the AKS cluster.
  assignments = {
    controlplane_subnet = {
      scope                = dependency.vnet.outputs.subnet_ids["aksnet-001"]
      principal_id         = dependency.controlplane_uami.outputs.principal_id
      type                 = "ServicePrincipal"
      role_definition_name = "Network Contributor"
    }
    controlplane_kubelet = {
      scope                = dependency.kubelet_uami.outputs.id
      principal_id         = dependency.controlplane_uami.outputs.principal_id
      type                 = "ServicePrincipal"
      role_definition_name = "Managed Identity Operator"
    }
  }
}
