
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "/home/ryanjks/CodeHaven/Personal-Projects/platform-infrastructure/infrastructure/azure/modules//lookup"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: (variable user_mails did not define a description)
  # Type: list
  # user_mails = []

  # Description: (variable group_names did not define a description)
  # Type: list
  # group_names = []

  # Description: (variable service_principal_names did not define a description)
  # Type: list
  # service_principal_names = []

  # Description: (variable ignore_missing did not define a description)
  # Type: object
  # ignore_missing = {"azuread_groups":true,"azuread_service_principals":true,"azuread_users":true}

}
